
[domains]
blacklists = [
    ["uribl.abuse.ro", "abuse.ro URI Blacklist"],
    ["bl.fmb.la", "fmb.la Blacklist"],
    ["fresh.fmb.la", "fmb.la New Domain List"],
    ["black.junkemailfilter.com", "junkemailfilter.com Blacklist"],
    ["uribl.mailcleaner.net", "mailcleaner.net URI Blacklist"],
    ["dbl.nordspam.com", "NordSpam Domain Blacklist"],
    ["ubl.nszones.com", "nszones.com Universal Blacklist"],
    ["uribl.pofon.foobar.hu", "pofon.foobar.hu URI Blacklist"],
    ["rhsbl.rbl.polspam.pl", "polspam.pl URI Blacklist"],
    ["rhsbl-h.rbl.polspam.pl", "polspam.pl Strict URI Blacklist"],
    ["mailsl.dnsbl.rjek.com", "rjek.com URI Shitlist"],
    ["uribl.rspamd.com", "rspamd.com URI Blacklist"],
    ["rhsbl.rymsho.ru", "rymsho.ru Domain Blacklist"],
    ["public.sarbl.org", "sarbl.org Domain Blacklist"],
    ["rhsbl.scientificspam.net", "scientificspam.net Domain Blacklist"],
    ["uribl.spameatingmonkey.net", "SpamEatingMonkey URI Blacklist"],
    ["dbl.spamhaus.org", "spamhaus.org Domain Blacklist"],
    ["abuse.spfbl.net", "spfbl.net Abuse List"],
    ["dnsbl.spfbl.net", "spfbl.net Reputation Blacklist"],
    ["dbl.suomispam.net", "suomispam.net Domain Blacklist"],
    ["multi.surbl.org", "surbl.org Reputation Blacklist"],
    ["uribl.swinog.ch", "swinog.ch URI Blacklist"],
    ["dob.sibl.support-intelligence.net", "DayOldBread Domain Blacklist"],
    ["black.uribl.com", "uribl.com Domain Blacklist"],
    ["uri.blacklist.woody.ch", "woody.ch URI Blacklist"],
    ["rhsbl.zapbl.net", "zapbl.net Domain Blacklist"],
    ["d.bl.zenrbl.pl" "zenrbl.pl Domain Blacklist"]
]

greylists = [
    ["hostkarma.junkemailfilter.com", "junkemailfilter.com Reputation List"],
    ["reputation-domain.rbl.scrolloutf1.com", "Scrollout F1 Domain Reputation List"],
    ["freshzero.spameatingmonkey.net", "SpamEatingMonkey New Domains List"],
    ["fresh.spameatingmonkey.net", "SpamEatingMonkey Domain < 5 Days Old List"],
    ["fresh10.spameatingmonkey.net", "SpamEatingMonkey Domain < 10 Days Old List"],
    ["fresh15.spameatingmonkey.net", "SpamEatingMonkey Domain < 15 Days Old List"],
    ["fresh30.spameatingmonkey.net", "SpamEatingMonkey Domain < 30 Days Old List"],
    ["urired.spameatingmonkey.net", "SpamEatingMonkey URI Greylist"],
    ["grey.uribl.com", "uribl.com Domain Greylist"],
    ["red.uribl.com", "uribl.com Domain Suspected Abuse List"],
]

ipv4_blacklists = [

]

ipv6_blacklists = [

]
